export interface EventTemplate {
  id: string;
  name: string;
  category: "wedding" | "festival" | "corporate" | "party" | "educational" | "commercial";
  themeColor: string;
  accentColor: string;
  bgGradient: string;
  iconName: string;
  tagline: string;
  coverImage: string;
  qrPosterStyle: "mandap" | "dandiya" | "royal" | "corporate" | "festive" | "minimal";
  badgeText: string;
}

export const EVENT_TEMPLATES: EventTemplate[] = [
  // 1. WEDDING & CEREMONIES
  {
    id: "royal-wedding",
    name: "Royal Wedding",
    category: "wedding",
    themeColor: "#ff5429",
    accentColor: "#fbbf24",
    bgGradient: "from-amber-950/40 via-[#06080e] to-slate-950",
    iconName: "Heart",
    tagline: "Relive Every Royal Moment of Our Special Day!",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200",
    qrPosterStyle: "mandap",
    badgeText: "Most Popular",
  },
  {
    id: "sangeet-night",
    name: "Sangeet & Dance Night",
    category: "wedding",
    themeColor: "#ec4899",
    accentColor: "#8b5cf6",
    bgGradient: "from-pink-950/40 via-[#06080e] to-purple-950/40",
    iconName: "Music",
    tagline: "Capture the Beats, Dance Moves & Celebration Energy!",
    coverImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200",
    qrPosterStyle: "royal",
    badgeText: "High Energy",
  },
  {
    id: "mehendi-ceremony",
    name: "Mehendi Ceremony",
    category: "wedding",
    themeColor: "#10b981",
    accentColor: "#f59e0b",
    bgGradient: "from-emerald-950/40 via-[#06080e] to-amber-950/40",
    iconName: "Sparkles",
    tagline: "Share Henna Designs, Laughs & Festive Wishes!",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200",
    qrPosterStyle: "mandap",
    badgeText: "Traditional",
  },
  {
    id: "haldi-ceremony",
    name: "Haldi Utsav",
    category: "wedding",
    themeColor: "#f59e0b",
    accentColor: "#ea580c",
    bgGradient: "from-amber-950/50 via-[#06080e] to-orange-950/40",
    iconName: "Sun",
    tagline: "Golden Blessings & Vibrant Haldi Moments!",
    coverImage: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Golden Vibes",
  },
  {
    id: "engagement-ceremony",
    name: "Ring Ceremony & Engagement",
    category: "wedding",
    themeColor: "#6366f1",
    accentColor: "#fbbf24",
    bgGradient: "from-indigo-950/40 via-[#06080e] to-slate-950",
    iconName: "Gem",
    tagline: "Two Hearts Joined. Share Your Love & Blessings!",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200",
    qrPosterStyle: "royal",
    badgeText: "Elegant",
  },
  {
    id: "reception-gala",
    name: "Grand Reception Gala",
    category: "wedding",
    themeColor: "#e11d48",
    accentColor: "#f59e0b",
    bgGradient: "from-rose-950/40 via-[#06080e] to-slate-950",
    iconName: "PartyPopper",
    tagline: "A Night of Grandeur & Timeless Memories!",
    coverImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200",
    qrPosterStyle: "mandap",
    badgeText: "Luxury",
  },
  {
    id: "baby-shower",
    name: "Godh Bharai / Baby Shower",
    category: "wedding",
    themeColor: "#06b6d4",
    accentColor: "#f472b6",
    bgGradient: "from-cyan-950/40 via-[#06080e] to-pink-950/40",
    iconName: "Baby",
    tagline: "Welcoming Little Miracles with Love & Joy!",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Heartwarming",
  },

  // 2. INDIAN FESTIVALS & RELIGIOUS UTSAVS
  {
    id: "ganesh-chaturthi",
    name: "Ganesh Chaturthi Utsav",
    category: "festival",
    themeColor: "#ff5429",
    accentColor: "#f59e0b",
    bgGradient: "from-orange-950/50 via-[#06080e] to-amber-950/50",
    iconName: "Flame",
    tagline: "Ganpati Bappa Morya! Share Darshan & Aarti Memories!",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Bappa Utsav",
  },
  {
    id: "navratri-garba",
    name: "Navratri Garba & Dandiya Raas",
    category: "festival",
    themeColor: "#8b5cf6",
    accentColor: "#ec4899",
    bgGradient: "from-purple-950/50 via-[#06080e] to-pink-950/50",
    iconName: "Sparkles",
    tagline: "Chalo Garba! Share Your Colorful Chaniya Choli & Dance Snaps!",
    coverImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200",
    qrPosterStyle: "dandiya",
    badgeText: "Garba Night",
  },
  {
    id: "diwali-gala",
    name: "Diwali Deepotsav Gala",
    category: "festival",
    themeColor: "#f59e0b",
    accentColor: "#ef4444",
    bgGradient: "from-amber-950/60 via-[#06080e] to-red-950/50",
    iconName: "Sun",
    tagline: "Festival of Lights! Capture Diya Glow & Rangoli Smiles!",
    coverImage: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Deepotsav",
  },
  {
    id: "holi-utsav",
    name: "Holi Festival of Colors",
    category: "festival",
    themeColor: "#ec4899",
    accentColor: "#06b6d4",
    bgGradient: "from-pink-950/40 via-[#06080e] to-cyan-950/40",
    iconName: "Flame",
    tagline: "Rang Barse! Share Your Vibrant Gulal & Joyful Celebrations!",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Vibrant Colors",
  },
  {
    id: "janmashtami-utsav",
    name: "Janmashtami Dahi Handi",
    category: "festival",
    themeColor: "#3b82f6",
    accentColor: "#fbbf24",
    bgGradient: "from-blue-950/50 via-[#06080e] to-amber-950/40",
    iconName: "Crown",
    tagline: "Govinda Aala Re! Capture Human Pyramids & Festivities!",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Dahi Handi",
  },
  {
    id: "raksha-bandhan",
    name: "Raksha Bandhan Celebration",
    category: "festival",
    themeColor: "#10b981",
    accentColor: "#f59e0b",
    bgGradient: "from-emerald-950/40 via-[#06080e] to-slate-950",
    iconName: "Heart",
    tagline: "Celebrating Sibling Bond & Lifetime Promises!",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Family Bond",
  },

  // 3. CORPORATE & COMMERCIAL
  {
    id: "corporate-summit",
    name: "Corporate Annual Summit",
    category: "corporate",
    themeColor: "#3b82f6",
    accentColor: "#64748b",
    bgGradient: "from-slate-900 via-[#06080e] to-blue-950/40",
    iconName: "Briefcase",
    tagline: "Keynotes, Networking & Executive Team Highlights!",
    coverImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200",
    qrPosterStyle: "corporate",
    badgeText: "Enterprise",
  },
  {
    id: "product-launch",
    name: "Product Launch Gala",
    category: "corporate",
    themeColor: "#6366f1",
    accentColor: "#38bdf8",
    bgGradient: "from-indigo-950/50 via-[#06080e] to-slate-950",
    iconName: "Zap",
    tagline: "Unveiling Innovation! Share Attendee Snaps & Impressions!",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200",
    qrPosterStyle: "corporate",
    badgeText: "Innovation",
  },
  {
    id: "hotel-cafe-events",
    name: "Hotels, Cafes & Venues",
    category: "commercial",
    themeColor: "#14b8a6",
    accentColor: "#f59e0b",
    bgGradient: "from-teal-950/40 via-[#06080e] to-slate-950",
    iconName: "Hotel",
    tagline: "Value-Added Memory Album for Hospitality Guests!",
    coverImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200",
    qrPosterStyle: "corporate",
    badgeText: "Hospitality",
  },

  // 4. PARTIES & EDUCATIONAL
  {
    id: "birthday-bash",
    name: "Birthday Party Bash",
    category: "party",
    themeColor: "#f43f5e",
    accentColor: "#facc15",
    bgGradient: "from-rose-950/40 via-[#06080e] to-amber-950/40",
    iconName: "Cake",
    tagline: "Cheers to Another Year! Share Wishes & Funny Cake Snaps!",
    coverImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200",
    qrPosterStyle: "festive",
    badgeText: "Celebration",
  },
  {
    id: "college-fest",
    name: "College Convocation & Fest",
    category: "educational",
    themeColor: "#10b981",
    accentColor: "#3b82f6",
    bgGradient: "from-emerald-950/40 via-[#06080e] to-blue-950/40",
    iconName: "GraduationCap",
    tagline: "Class of 2026! Capture Graduation Joy & Campus Memories!",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200",
    qrPosterStyle: "minimal",
    badgeText: "Graduation",
  }
];

export function getTemplateById(id: string): EventTemplate {
  return EVENT_TEMPLATES.find((t) => t.id === id) || EVENT_TEMPLATES[0];
}
